#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 11 09:36:38 2019

@author: lillian
"""

with open('cherbonnel-mi-tio_SP.txt') as file_object:
    contents = file_object.read()
    print(contents)#prints file
s = contents.split()
print(str(s))


for word in s:
   x = (word.strip('|©¡!@#$%^&*()--_=+,.;:?/<>''¿[]'))


counts = {}
for word in s:
    if not word in counts:
        counts[word] = 0
    counts[word] += 1
print(counts)
    
    

            